language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
install: "pip install -r requirements.txt"
os:
 - osx
 - linux
notifications:
   email: false
script:
  -py.test test --doctest-modules -v --cov cargo --cov-report term-missing -pep8
after_success:
  - coveralls
