language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
install: "pip install -e ."
os:
 - osx
 - linux
notifications:
   email: false
script:
  - py.test test --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls
