"""empty message

Revision ID: 7829e2406e
Revises: None
Create Date: 2015-07-12 19:11:45.077763

"""

# revision identifiers, used by Alembic.
revision = '7829e2406e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
